<a href="https://colab.research.google.com/github/JuanFdoGf/PruebaGitHub/blob/main/Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import numpy as np

## Basic Numpy Arrays

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
b = np.array([0, .5, 1, 1.5, 2.])

In [ ]:
a[0], a[2]

(np.int64(1), np.int64(3))

In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
b[0:2]

array([0. , 0.5])

In [ ]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

## Dimensions and shapes

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1],
    ]
])

In [ ]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

## Indexing and Slicing of Matrices

In [ ]:
#Square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][0]

np.int64(4)

In [ ]:
A[1, 0]

np.int64(4)

In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[: ,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1] = np.array([10, 10, 10])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A[2] = 99

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Summary statistics

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.sum()

np.int64(10)

In [ ]:
a.mean()

np.float64(2.5)

In [ ]:
a.std()

np.float64(1.118033988749895)

In [ ]:
a.var()

np.float64(1.25)

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A.sum()

np.int64(45)

In [ ]:
A.mean()

np.float64(5.0)

In [ ]:
A.std()

np.float64(2.581988897471611)

In [ ]:
A.sum(axis=0)

array([12, 15, 18])

In [ ]:
A.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
A.mean(axis=0)

array([4., 5., 6.])

In [ ]:
A.mean(axis=1)

array([2., 5., 8.])

In [ ]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

## Broadcasting and Vectorized Opetations

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a + 10

array([10, 11, 12, 13])

In [ ]:
a * 10

array([ 0, 10, 20, 30])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a += 100

In [ ]:
a

array([100, 101, 102, 103])

In [ ]:
l = [0, 1, 2, 3]

In [ ]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
b = np.array([10, 10, 10, 10])

In [ ]:
a + b

array([10, 11, 12, 13])

In [ ]:
a * b

array([ 0, 10, 20, 30])

## Boolean arrays

In [ ]:
a = np.arange(4)

In [ ]:
a

In [ ]:
a[[0, -1]]

In [ ]:
a[[True, False, False, True]]

In [ ]:
a >= 2

In [ ]:
a[a >= 2]

In [ ]:
a.mean()

In [ ]:
a[a > a.mean()]

In [ ]:
a[~(a > a.mean())]

In [ ]:
a[(a == 0) | (a == 1)]

In [ ]:
a[(a >= 2) & (a % 2 == 0)]

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

In [ ]:
A > 30