In [2]:
import sys
import numpy as np

## Basic Numpy Arrays

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
a = np.array([1, 2, 3, 4])

In [11]:
b = np.array([0, .5, 1, 1.5, 2.])

In [7]:
a[0], a[2]

(np.int64(1), np.int64(3))

In [8]:
a[0:]

array([1, 2, 3, 4])

In [9]:
a[1:3]

array([2, 3])

In [15]:
b[0:2]

array([0. , 0.5])

In [16]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

## Dimensions and shapes

In [17]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [18]:
A.shape

(2, 3)

In [21]:
A.ndim

2

In [19]:
A.size

6

In [22]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1],
    ]
])

In [23]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [24]:
B.shape

(2, 2, 3)

In [25]:
B.ndim

3

In [26]:
B.size

12

## Indexing and Slicing of Matrices

In [27]:
#Square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [28]:
A[1]

array([4, 5, 6])

In [29]:
A[1][0]

np.int64(4)

In [30]:
A[1, 0]

np.int64(4)

In [31]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
A[: ,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [33]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
A[1] = np.array([10, 10, 10])

In [35]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [36]:
A[2] = 99

In [37]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Summary statistics

In [3]:
a = np.array([1, 2, 3, 4])

In [41]:
a.sum()

np.int64(10)

In [42]:
a.mean()

np.float64(2.5)

In [4]:
a.std()

np.float64(1.118033988749895)

In [44]:
a.var()

np.float64(1.25)

In [5]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [6]:
A.sum()

np.int64(45)

In [7]:
A.mean()

np.float64(5.0)

In [8]:
A.std()

np.float64(2.581988897471611)

In [9]:
A.sum(axis=0)

array([12, 15, 18])

In [10]:
A.sum(axis=1)

array([ 6, 15, 24])

In [11]:
A.mean(axis=0)

array([4., 5., 6.])

In [12]:
A.mean(axis=1)

array([2., 5., 8.])

In [13]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [14]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

## Broadcasting and Vectorized Opetations

In [15]:
a = np.arange(4)

In [16]:
a

array([0, 1, 2, 3])

In [17]:
a + 10

array([10, 11, 12, 13])

In [18]:
a * 10

array([ 0, 10, 20, 30])

In [19]:
a

array([0, 1, 2, 3])

In [20]:
a += 100

In [21]:
a

array([100, 101, 102, 103])

In [22]:
l = [0, 1, 2, 3]

In [23]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [24]:
a = np.arange(4)

In [25]:
a

array([0, 1, 2, 3])

In [28]:
b = np.array([10, 10, 10, 10])

In [29]:
a + b

array([10, 11, 12, 13])

In [30]:
a * b

array([ 0, 10, 20, 30])

## Boolean arrays

In [ ]:
a = np.arange(4)

In [ ]:
a

In [ ]:
a[[0, -1]]

In [ ]:
a[[True, False, False, True]]

In [ ]:
a >= 2

In [ ]:
a[a >= 2]

In [ ]:
a.mean()

In [ ]:
a[a > a.mean()]

In [ ]:
a[~(a > a.mean())]

In [ ]:
a[(a == 0) | (a == 1)]

In [ ]:
a[(a >= 2) & (a % 2 == 0)]

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

In [ ]:
A > 30